apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-nfs-pv
  namespace: wp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wp-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/k8s-wordpress
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs-pvc
  namespace: wp
spec:
  storageClassName: wp-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi