apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wp-nfs-pv
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: db_user
            - name: WORDPRESS_DB_PASSWORD
              value: db_password

      volumes:
        - name: wp-nfs-pv
          persistentVolumeClaim:
            claimName: wp-nfs-pvc