apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpmysql-nfs-pv
  namespace: wp-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wp-nfs-test
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/k8s-wp-data/mysql
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-nfs-pv
  namespace: wp-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wp-nfs-test
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/k8s-wp-data/wordpress
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-nfs-pvc
  namespace: wp-test
  labels:
        app: wordpress
spec:
  storageClassName: wp-nfs-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpmysql-nfs-pvc
  namespace: wp-test
  labels:
        app: mysql
spec:
  storageClassName: wp-nfs-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi