apiVersion: v1
kind: Service
metadata:
  name: wp-svc-test
  namespace: wp-test
spec:
  selector:
    app: wordpress
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31100
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-test
  namespace: wp-test
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: LoadBalancer