apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wpdb
  name: wpdb
spec:
  containers:
  - name: wpdb
    image: mysql:5.7
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: Paulco#@29$%
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      value: Paulco#@29$%
    
    
